version: '3.7'
services:
  minecraft:
    image: itzg/minecraft-server
    tty: true
    stdin_open: true
    ports:
      - "25565:25565"
      - "19132:19132"
    environment:
      EULA: "TRUE"
      DIFFICULTY: "NORMAL"
      ONLINE_MODE: "FALSE"
      PLUGINS: "https://download.geysermc.org/v2/projects/geyser/versions/latest/builds/latest/downloads/spigot,https://download.geysermc.org/v2/projects/floodgate/versions/latest/builds/latest/downloads/spigot"
    volumes:
      - ./data:/data
